### ISSUE TITLE
Exited with code: 255 on osx 10.8.3

### ISSUE THREAD

**Issue by bonsak** [andreberg/C4D-Plugin-Wizard#1]
Great idea André! This is awsome. But when trying to start the app on osx 10.8.3 i get this error in the console: 
10/9/13 10:05:36.903 AM com.apple.launchd.peruser.501[166]: ([0x0-0x2e26e24].com.seramediavfx.C4DPluginWizard[41461]) Exited with code: 255

**Comment by andreberg** [comment]
Thanks a lot for trying it out and bringing this issue to my attention....

Well, that is curious. I am on 10.8.5 but that shouldn't be the issue. Could it be a gatekeeper issue? Did you double click the app or did you use right click, then "open" ?

The only other mac I have is a 10.6 system and last time I tried it opened without issues.

**Comment by bonsak** [comment]
Gatekeeper is set to "Anywhere". No its the same result with both dobble-click and right-click "open" Just out of curiosity i tried starting the app from the commandline:

```
/Applications/Maxon/CINEMA_4D_Plugin_Wizard_(OSX)/CINEMA 4D Plugin Wizard.app/Contents/MacOS/CINEMA 4D Plugin Wizard
```

But then i got this back:

```
Traceback (most recent call last):
  File "<string>", line 31, in <module>
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\iu.py", line 449, in doimport
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\iu.py", line 248, in getmod
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\archive.py", line 495, in getmod
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\iu.py", line 105, in getmod
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\iu.py", line 449, in doimport
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\iu.py", line 248, in getmod
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\archive.py", line 495, in getmod
  File "C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0\PyInstaller\loader\iu.py", line 105, in getmod
ImportError: dlopen(/var/folders/ql/759nyx4x28d9m4h2lwqq23pw0000gn/T//_MEICd4JBW/PyQt4._qt.so, 2): Library not loaded: @loader_path/libQtCLucene.4.dylib
  Referenced from: /var/folders/ql/759nyx4x28d9m4h2lwqq23pw0000gn/T//_MEICd4JBW/QtHelp
  Reason: image not found
```

Were using Deadline from Thinkbox wich uses PyQt so it it could be some environment thing on my end.

**Comment by andreberg** [comment]
Can you try re-downloading from the blog post please? 
Here's the link again: http://bit.ly/15mky9E

`C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\source\pyinstaller-2.0` is actually the path on my Windows system where I put the PyInstaller script that compiled the exectuable. 

I am baffled as to what that path is doing in the OS X executable. I had a hunch that maybe my synchronization software somehow copied artifacts from the build dir on my Windows machine to the OS X machine where parts of it where compiled into the OS X executable.

So, I cleaned my environment, re-downloaded a fresh copy of PyInstaller and recompiled the OS X version. 
It's a long shot but maybe it works for you...

**Comment by bonsak** [comment]
Hm. It still gives the same error in the console and it still points back to something on your machine it seems:

```
Bonsak-work:MacOS bonsak$ "./cinema 4d plugin wizard"
Traceback (most recent call last):
  File "<string>", line 31, in <module>
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/iu.py", line 386, in importHook
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/iu.py", line 449, in doimport
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/iu.py", line 248, in getmod
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/archive.py", line 495, in getmod
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/iu.py", line 105, in getmod
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/iu.py", line 386, in importHook
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/iu.py", line 449, in doimport
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/iu.py", line 248, in getmod
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/archive.py", line 495, in getmod
  File "/Users/andre/source/pyinstaller-2.0/PyInstaller/loader/iu.py", line 105, in getmod
ImportError: dlopen(/var/folders/ql/759nyx4x28d9m4h2lwqq23pw0000gn/T//_MEIDiYlyc/PyQt4._qt.so, 2): Library not loaded: @loader_path/libQtCLucene.4.dylib
  Referenced from: /var/folders/ql/759nyx4x28d9m4h2lwqq23pw0000gn/T//_MEIDiYlyc/QtHelp
  Reason: image not found
```

**Comment by andreberg** [comment]
Aha! There seems to be an issue with PyInstaller encoding incorrect dylib paths on OS X... 

I will try the solution suggested here (http://www.pyinstaller.org/ticket/595) and recompile a new version. 
Let's hope this does the trick.

I am not even using that libQtCLucene library in my code but the ticket is correct. That is the only library from Qt that is in  /usr/lib for some reason.

**Comment by andreberg** [comment]
Alright, new version is up. I did the fix to the .spec file as suggested by that ticket and recompiled. I replaced the dropbox upload so you can download from the blog post again as before.

Fingers crossed.

**Comment by bonsak** [comment]
It works! Thanks alot!
